- src/cli.rs
Figure I should push this first.
Adds a global `--dir` when it's included, we change directories to the given folder before doing anything.
Super simple, super useful.
enables this while developing: `cargo run -- -d ../norg_blog serve`
> feat: --dir flag to act on a different working directory

- .github/workflows/build.yml
- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- src/cmd/init.rs
- src/cmd/serve.rs
This change creates a new instance of Tera in the `serve` function instead of starting a new one every time a new request is made to the server, thus avoiding unnecessary reloads of templates while also implementing a file watcher system using `notify` and a debouncer using `notify-debouncer-full` to avoid spamming the stdout when modifying files.
Edit: this PR also uses Tera's `Context` to render the contents of `norg` files directly into the `base.html` template to avoid having to create a `current.html` template in memory for each request.
> fix: do not continuously recompile HTML templates during `serve`

- Cargo.lock
- src/cmd/serve.rs
- Implement live reload functionality using watch channel and client-side script injection
- Add MIME type detection for static assets (CSS, JS, images)
- Optimize content conversion by only rebuilding changed files
- Separate template reloading from content regeneration with debounced watchers
- Improve error handling and logging throughout server operations
- Add ServerState structure to manage reload signaling and template engine
- Implement proper content-type headers for HTTP responses
- Enhance file change detection with filtered event handling for templates and content
> feat(serve): add live reload support with template/content watching and improved asset handling

- Cargo.lock
- Cargo.toml
- src/cmd/init.rs
- src/cmd/serve.rs
- src/config.rs
- src/main.rs
- src/templates/base.html
- src/tera_functions.rs
- Add `SiteConfig` struct with serde-derived serialization/deserialization
- Integrate site configuration into server state and template rendering context
- Create dedicated base template file with dynamic config values
- Add custom Tera `now` function for datetime formatting in templates
- Include `author` field in generated site configuration during init
- Preserve template directory structure in `init` command
- Update template to use config values for `language`, `title`, and `author`
- Add proper error handling for config file parsing
- Register custom tera functions in template engine initialization
- Centralize template assets using `include_str!` for better maintenance
---
Resolves #5
> feat(config): implement structured site configuration and enhance template system

- Cargo.toml
- README.md
After a small discussion to decide a shorter name for the produced Norgolith binary, we ended up choosing `lith`. It is a clever, ergonomic and meaningful shortening of "Norgolith" that carries both technical and symbolic weight to the project.
The suffix "-lith" comes directly from the full name Norgolith, which itself derives from "monolithic", that is a key descriptor for the project. "Lith" also originates from the Greek word lithos, meaning "stone" or "rock", which ties into the idea of stability, durability, and permanence—traits that align with the Norgolith project README description.
Typing any Norgolith command will be effortless now, e.g. `lith serve` vs `norgolith serve`.
> ref!: rename binary from `norgolith` to `lith`

- Cargo.lock
- Cargo.toml
- src/cmd/new.rs
- src/cmd/serve.rs
- src/converter/meta.rs
- src/fs.rs
- Implement MIME type detection for static assets using `mime_guess` crate
- Add dedicated assets directory watching with hot reload support
- Improve filesystem path resolution with mutable current_dir reference
- Enhance content conversion logging with cleaner path display
- Expand ignore patterns for editor backup files (~) in watcher
- Refactor template/content change detection with directory-aware checks
- Add asset change handling endpoint with proper error responses
- Update `fs::find_in_previous_dirs` to support passing an initial directory
> feat(assets): add proper asset handling and MIME type support

- src/cmd/init.rs
- src/cmd/new.rs
- src/cmd/serve.rs
- src/converter/meta.rs
- src/fs.rs
- src/tera_functions.rs
Norgolith will now attempt to load a custom `template` based on the `layout` metadata field in the norg files.
I haven't tested with nested templates in directories (e.g. `layout: foo/bar` -> `templates/foo/bar.html`), but the way templates are currently loaded it should work fine.
> feat(serve): add custom templates loading

- src/cmd/init.rs
- src/cmd/serve.rs
- src/resources/content/index.norg
- src/resources/templates/base.html
- src/resources/templates/default.html
- Add template inheritance system with base/default HTML structure
- Create separate template files in resources directory
- Add `default.html` as primary content template extending `base.html`
- Move `index.norg` content to dedicated resource file
- Implement dynamic template loading during site initialization
- Update init command to create multiple template files
- Create default template structure with base/default separation
- Use resource embedding for template/content files
- Change default layout from `base` to `default` in server logic
- Implement proper template blocks (title/content) for inheritance
- Add dynamic metadata injection in default template title
- Improve new site initialization content with proper metadata examples
Note: This is a breaking change because it changes …
> feat(templates)!: implement structured template inheritance and default layouts

- src/cmd/init.rs
- src/config.rs
- src/resources/templates/base.html
- Implement `highlighter` config section in site configuration
- Add `PrismJS` and `Highlight.js` loading logic to base template
- Support engine selection between `prism`/`hljs` in templates
- Include CDN resources for both highlighting engines
- Add error handling for invalid engine selection through window alerts
- Update `init` command template with default highlighting config
- Maintain backwards compatibility with highlighting disabled by default
Closes #37
> feat: add syntax highlighting configuration options

- src/converter/html.rs
Currently it only works for embedding HTML code
> feat(converter): add partial support for `@embed` tags

- src/resources/content/index.norg
- src/resources/templates/base.html
Note that the Play CDN is meant to be used only for development purposes, and is not intended for production. A proper Tailwind CLI setup should be used later by the end user.
> feat: ship TailwindCSS Play CDN by default

- src/converter/html.rs
- Prevent list-level HTML carryover tags from affecting nested content
- Create clean carryover context for list item text conversion
- Resolve unintended attribute inheritance in list structures
- Maintain proper HTML attribute scoping within list items
> fix(converter): isolate list item content from parent carryover tags

- src/cmd/build.rs
This lets us copy any asset file format including images and not only text file formats
> fix(build): copy files content as binary

- src/cli.rs
- src/cmd/build.rs
- src/cmd/serve.rs
- src/shared/mod.rs
`lith serve` will build draft content by default (as if `--drafts` flag has been passed to the command). To disable this behaviour, use `--no-drafts`.
`lith build` will completely ignore any draft content.
Closes #56
> feat: handle `draft` content properly

- Cargo.lock
- Cargo.toml
- flake.nix
- src/cli.rs
- src/cmd/build.rs
- src/cmd/mod.rs
- src/cmd/serve.rs
- src/cmd/theme.rs
- src/fs.rs
- src/main.rs
- src/shared/mod.rs
- src/theme.rs
- Add `lith theme` subcommands for theme lifecycle management
- Support `install`/`update`/`info` operations with semantic versioning
- Add repository shorthand resolution (`gh:|github:`/`berg:|codeberg:` prefixes)
- Integrate theme templates into rendering pipeline
- Load theme templates from theme/templates with lower priority than user templates
- Maintain template override hierarchy for user customization
- Add `ThemeManager` struct for handling theme operations
- Track `repository`, `version`, and `pin` status in metadata
- Prepare foundation for git-based theme fetching
- Update build/serve commands to include theme assets
- Ensure theme resources are available during site generation
- Add `theme` directory to Tera initialization
- Add `semver` dependency for version constraint …
> feat(themes): implement theme management system

- Cargo.lock
- src/cmd/build.rs
- src/cmd/serve.rs
- src/config.rs
- src/main.rs
- src/schema/mod.rs
- src/schema/validator.rs
> feat: implement content metadata validation

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/cmd/build.rs
- src/cmd/new.rs
- src/cmd/serve.rs
- src/fs.rs
- src/shared/mod.rs
Refactored commands:
Note for myself: I've added a `find_config_file` function in the `fs` module. I should use it on each command later (already implemented it on `serve`).
> ref!: overhaul the commands codebase

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/cmd/serve.rs
It would be great to also add support for passing an IPv4 address to `--host` instead of keeping it as a boolean argument, similar to what [Vite](https://vite.dev/config/server-options#server-host) does (cc `@remrevo2048`).
Resolves #79
---
NB: this PR also added the `colored` crate, which will be used to prettify the logs even more later on.
> feat(serve): add support for `--host` to expose server to LAN address

- Cargo.lock
- Cargo.toml
Enabled `preserve_order` features in both `toml` and `tera` crates. This should avoid any unexpected issue with the order in for loops and such things in the templates.
> feat: enable `preserve_order` features

- src/cmd/build.rs
- src/cmd/serve.rs
- src/shared/mod.rs
- src/tera_functions.rs
This commit adds the possibility to expose all content files at `my-site/posts/` which are then accessible inside the templates allowing for some niceties like creating a Recent posts list template.
It does expose a `posts` array as part of the templates context, which holds the metadata from all the blog posts including an extra `permalink` field and also a `raw` field with the HTML code for the post.
> feat: expose posts pages to both server and build

- src/converter/html.rs
- src/converter/meta.rs
- src/shared/mod.rs
- src/tera_functions.rs
Usage example (taken from the Tailwind theme I'm cooking):
```html
{% if metadata.toc %}
{% set toc_html = generate_toc(toc=metadata.toc, list_type="ol") %}
<h3>Table of Contents</h3>
<nav class="toc">
{{ toc_html | safe }}
</nav>
{% endif %}
```
> feat: add support for Table of Contents

- Cargo.lock
- Cargo.toml
- src/cmd/build.rs
- src/cmd/init.rs
- src/config.rs
- src/resources/templates/rss.xml
- src/shared/mod.rs
RSS is enabled by default. The default [ttl](https://www.rssboard.org/rss-specification#ltttlgtSubelementOfLtchannelgt) value is `60`.
Configuration options (and their defaults):
```toml
[rss]
enable = true
description = 'Latest posts'
ttl = 60
```
There is a default modifiable template for RSS in `templates/rss.xml` when creating a new site. Adapting an existing site for using RSS is as simple as creating the file and pasting the defaults:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>{{ config.title }}</title>
<link>{{ config.rootUrl | escape_xml | safe }}</link>
<description>{{ config.rss.description | default(value="Latest posts")}}</description>
<generator>Norgolith</generator>
<language>{{ config.language …
```
> feat: add support for RSS feeds

- src/cmd/build.rs
- src/cmd/init.rs
- src/cmd/serve.rs
- src/resources/templates/categories.html
- src/resources/templates/category.html
- src/shared/mod.rs
Default templates for `category.html` and `categories.html` are generated on `lith init`, existing sites can grab them from [src/resources/templates](https://github.com/NTBBloodbath/norgolith/tree/master/src/resources/templates).
There are two new special routes, `/categories` and `/categories/[category]` which should be automatically generated on both `build` or `serve`.
> feat: implement taxonomies using `categories`

- src/cli.rs
- src/config/commands.rs
- src/config/mod.rs
Allows setting commands configuration directly in the `norgolith.toml`.
E.g.
```toml
[serve]
port = 8080 # Use 8080 as the default instead of 3030
open = true # Automatically open the web browser page
host = true # Expose server to LAN
[build]
minify = false # Do not minify artifacts
```
Closes #83
> feat(config): allow setting commands configuration in the site configuration file

- Cargo.toml
I setup fresh machine and found that I couldn't build the norgolith due to unincluded dependencies.
So include `vendored` features in `git2` for all targets by default.
> Fix: enable vendored git2 features for every targets

- flake.nix
It is failing to build OpenSSL otherwise using `nix build`
> fix: add perl to nativeBuildInputs

- src/cmd/build.rs
- src/cmd/dev.rs
Fixes issue mentioned in discord server by @Ladas552 https://discordapp.com/channels/834325286664929280/1272657884743860235/1377461059992027156
Now `build` subcommand will always ignore all draft posts in category page.
I'm considering to add `--drafts` option in `build` command too, but that will come after #117 is fixed
> fix(build): ignore draft posts on category page

- README.md
Add AUR instructions into the Readme.md and add a period at the end to 2 sentences
references issue: https://github.com/NTBBloodbath/norgolith/issues/119
Please add instructions to the Docs website branch too, I don't have access to it.
> docs(readme): add AUR package instructions
